version: "3"
services:
  # For Azure
  mock-oauth2-server:
    image: docker.pkg.github.com/navikt/mock-oauth2-server/mock-oauth2-server:0.1.33
    ports:
      - 1111:1111
  postgres-migrering:
    image: postgres:12
    environment:
      POSTGRES_USER: familie
      POSTGRES_DB: familiebamigrering
      POSTGRES_PASSWORD: familie-pwd
    ports:
      - 5439:5432
  wiremock:
    image: wiremock/wiremock
    ports:
      - 8300:8080