apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: familie-ba-migrering
  namespace: teamfamilie
  labels:
    team: teamfamilie

spec:
  image: {{ image }}
  port: 8098
  liveness:
    path: /internal/health/liveness
    initialDelay: 30
    failureThreshold: 10
  readiness:
    path: /internal/health/readiness
    initialDelay: 30
    failureThreshold: 10
  prometheus:
    enabled: true
    path: /internal/prometheus
  vault:
    enabled: false
  replicas:
    min: 1
    max: 1
    cpuThresholdPercentage: 50
  resources:
    limits:
      memory: 1024Mi
      cpu: "1"
    requests:
      memory: 512Mi
      cpu: 200m
  ingresses: # Optional. List of ingress URLs that will route HTTP traffic to the application.
    - https://familie-ba-migrering.dev.intern.nav.no
    - https://familie-ba-migrering.dev.nav.no
  secureLogs:
    enabled: true
  gcp: # Database
    sqlInstances:
      - type: POSTGRES_12
        name: familie-ba-migrering
        diskAutoresize: true
        autoBackupTime: "03:00"
        databases:
          - name: familie-ba-migrering
            envVarPrefix: DB
  azure:
    application:
      enabled: true
      claims:
        extra:
          - "NAVident"
        groups:
          - id: c62e908a-cf20-4ad0-b7b3-3ff6ca4bf38b # teamfamilie-forvaltning
          - id: 928636f4-fd0d-4149-978e-a6fb68bb19de # 0000-GA-STDAPPS - tilgang til prosessering
      tenant: trygdeetaten.no
      replyURLs:
        - "https://familie-ba-migrering.dev.intern.nav.no/swagger-ui/oauth2-redirect.html"
      singlePageApplication: true
  accessPolicy:
    inbound:
      rules:
        - application: familie-prosessering
          namespace: teamfamilie
          cluster: dev-gcp
        - application: ida
          namespace: traktor
          cluster: prod-fss
    outbound:
      rules:
        - application: familie-ba-infotrygd
          namespace: teamfamilie
          cluster: dev-fss
        - application: familie-ba-sak
          namespace: teamfamilie
          cluster: dev-fss
  env:
    - name: SPRING_PROFILES_ACTIVE
      value: preprod
    - name: JAVA_OPTS
      value: "-Xmx1g"
