migrering:
  aktivert: true
  antallPersoner:
    ordinær: 250
    ordinær.deltbosted: 250
    utvidet: 250
    utvidet.deltbosted: 250

spring:
  flyway:
    placeholders:
      ignoreIfProd: --

rolle:
  teamfamilie:
    forvalter: "3d718ae5-f25e-47a4-b4b3-084a97604c1d"

BA_SAK_SCOPE: api://prod-gcp.teamfamilie.familie-ba-sak/.default
BA_SAK_API_URL: https://familie-ba-sak.intern.nav.no/api

FAMILIE_BA_INFOTRYGD_SCOPE: api://prod-fss.teamfamilie.familie-ba-infotrygd/.default
FAMILIE_BA_INFOTRYGD_API_URL: https://familie-ba-infotrygd.prod-fss-pub.nais.io

FAMILIE_BA_INFOTRYGD_FEED_SCOPE: api://prod-fss.teamfamilie.familie-ba-infotrygd-feed/.default
FAMILIE_BA_INFOTRYGD_FEED_API_URL: https://familie-ba-infotrygd-feed.prod-fss-pub.nais.io/api
