application:
  name: familie-ba-migrering

server:
  port: 8098
  servlet:
    context-path: /

spring:
  autoconfigure.exclude: org.springframework.boot.autoconfigure.web.servlet.error.ErrorMvcAutoConfiguration
  main:
    allow-bean-definition-overriding: true
    banner-mode: "off"
  flyway:
    enabled: true
    placeholders:
      ignoreIfProd:
  datasource:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/familie-ba-migrering
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    hikari:
      maximum-pool-size: 5
      connection-test-query: "select 1"
      max-lifetime: 30000
      minimum-idle: 1
  data.rest.basePath: /api/data
management:
  endpoint.health.show-details: always
  endpoint.health.probes.enabled: true
  health.livenessState.enabled: true
  health.readinessState.enabled: true

  endpoints.web:
    exposure.include: info, health, metrics, prometheus
    base-path: "/internal"
  metrics.export.prometheus.enabled: true

springdoc:
  packages-to-scan: no.nav.familie.ba.migrering, no.nav.familie.prosessering
  paths-to-match: "/api/**"
  swagger-ui:
    oauth:
      use-pkce-with-authorization-code-grant: true
      client-id: ${AZURE_APP_CLIENT_ID}
      scope-separator: ","
    disable-swagger-default-url: true

no.nav.security.jwt:
  issuer.azuread:
    discoveryurl: ${AZURE_APP_WELL_KNOWN_URL}
    accepted_audience: ${AZURE_APP_CLIENT_ID}
    cookie_name: azure_token
  client:
    registration:
      ba-sak-clientcredentials:
        resource-url: ${BA_SAK_API_URL}
        token-endpoint-url: ${AZURE_OPENID_CONFIG_TOKEN_ENDPOINT}
        grant-type: client_credentials
        scope: ${BA_SAK_SCOPE}
        authentication:
          client-id: ${AZURE_APP_CLIENT_ID}
          client-secret: ${AZURE_APP_CLIENT_SECRET}
          client-auth-method: client_secret_basic
      familie-ba-infotrygd-clientcredentials:
        resource-url: ${FAMILIE_BA_INFOTRYGD_API_URL}
        token-endpoint-url: ${AZURE_OPENID_CONFIG_TOKEN_ENDPOINT}
        grant-type: client_credentials
        scope: ${FAMILIE_BA_INFOTRYGD_SCOPE}
        authentication:
          client-id: ${AZURE_APP_CLIENT_ID}
          client-secret: ${AZURE_APP_CLIENT_SECRET}
          client-auth-method: client_secret_basic

migrering:
  aktivert: false
  antallPersoner: 1

rolle:
  teamfamilie:
    forvalter: ""

API_SCOPE: api://${AZURE_APP_CLIENT_ID}/.default
