migrering:
  aktivert: true
  antallPersoner: 20

BA_SAK_SCOPE: api://dev-fss.teamfamilie.familie-ba-sak/.default
BA_SAK_API_URL: https://familie-ba-sak.dev-fss-pub.nais.io/api

FAMILIE_BA_INFOTRYGD_SCOPE: api://dev-fss.teamfamilie.familie-ba-infotrygd/.default
FAMILIE_BA_INFOTRYGD_API_URL: https://familie-ba-infotrygd.dev-fss-pub.nais.io

AUTHORIZATION_URL: https://login.microsoftonline.com/navq.onmicrosoft.com/oauth2/v2.0/authorize
TOKEN_URL: https://login.microsoftonline.com/navq.onmicrosoft.com/oauth2/v2.0/token