migrering:
  aktivert: true
  antallPersoner: 1

spring:
  flyway:
    placeholders:
      ignoreIfProd: --

rolle:
  teamfamilie:
    forvalter: "3d718ae5-f25e-47a4-b4b3-084a97604c1d"

BA_SAK_SCOPE: api://prod-fss.teamfamilie.familie-ba-sak/.default
BA_SAK_API_URL: https://familie-ba-sak.prod-fss-pub.nais.io/api

FAMILIE_BA_INFOTRYGD_SCOPE: api://prod-fss.teamfamilie.familie-ba-infotrygd/.default
FAMILIE_BA_INFOTRYGD_API_URL: https://familie-ba-infotrygd.prod-fss-pub.nais.io

AUTHORIZATION_URL: https://login.microsoftonline.com/navno.onmicrosoft.com/oauth2/v2.0/authorize
TOKEN_URL: https://login.microsoftonline.com/navno.onmicrosoft.com/oauth2/v2.0/token