BA_SAK_SCOPE: api://dev-fss.teamfamilie.familie-ba-sak/.default
BA_SAK_API_URL: https://familie-ba-sak.dev-fss-pub.nais.io/api

FAMILIE_BA_INFOTRYGD_SCOPE: api://dev-fss.teamfamilie.familie-ba-infotrygd/.default
FAMILIE_BA_INFOTRYGD_API_URL: https://familie-ba-infotrygd.dev-fss-pub.nais.io

migrering.aktivert: true


no.nav.security.jwt:
  issuer.azuread:
    discoveryurl: ${AZURE_APP_WELL_KNOWN_URL}
    accepted_audience: ${AZURE_APP_CLIENT_ID}
    cookie_name: azure_token