BA_SAK_SCOPE: api://prod-fss.teamfamilie.familie-ba-sak/.default
BA_SAK_API_URL: https://familie-ba-sak.prod-fss-pub.nais.io/api

FAMILIE_BA_INFOTRYGD_SCOPE: api://prod-fss.teamfamilie.familie-ba-infotrygd/.default
FAMILIE_BA_INFOTRYGD_API_URL: https://familie-ba-infotrygd.nais.adeo.no
